config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  ### API routes
  mount API::Root => "/"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  root "public#index"

  ### Marketing pages
  get "features", to: "public#features"
  get "features/producers", to: "public#producers"
  get "features/consumers", to: "public#consumers"
  get "features/api_admins", to: "public#api_admins"
  get "features/database_admins", to: "public#database_admins"
  get "pricing", to: "public#pricing"
  get "company", to: "public#company"
  get "about", to: "public#company"

  get "docs", to: "public#docs"
  get "status", to: "public#status"

  get "blog", to: "blog#index"
  get "blog/:id", to: "blog#show"
  # get "blog" => redirect("http://medium.com/schemabook")

  get "privacy", to: "public#privacy"
  get "terms", to: "public#terms"

  post "newsletters", to: "newsletters#create"
  get "newsletters", to: "newsletters#update"

  ### Application routes
  get "users", to: redirect("dashboards"), as: :user_root # creates user_root_path, used for after sign in path
  get "dashboards", to: "dashboards#index"
  get "documents", to: "documents#index"
  get "supports", to: "supports#index"

  # profiles (user is the resource)
  get "profiles/:id/edit", to: "profiles#edit", as: :edit_user_profile
  get "profiles/:id", to: "profiles#show", as: :user_profile
  patch "profiles/:id", to: "profiles#update", as: :patch_user_profile

  # stakeholders
  post "stakeholders", to: "stakeholders#create"

  # favorites
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"

  resources :teams, except: :index
  resources :businesses
  resources :services
  resources :schemas, param: :public_id do
    resources :validations, only: :create
    resources :webhooks
    resources :versions do
      resources :comments
    end
  end

  get "checkouts", to: "checkouts#new"
  post "checkouts", to: "checkouts#create"
  get "checkouts/success", to: "checkouts#success"
  get "checkouts/cancel", to: "checkouts#cancel"
  delete "checkouts/delete", to: "checkouts#delete"
end

app/models/service.rb
class Service < ApplicationRecord
  include PublicIdGenerator

  UNPAID_LIMIT = 10

  belongs_to :team
  has_many :schemas

  validates :name, presence: true, uniqueness: {scope: :team_id}
  validates :created_by, presence: true

  delegate :name, to: :team, prefix: true
  delegate :email, to: :team, prefix: true
  delegate :channel, to: :team, prefix: true

  def creator
    User.find created_by
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  # GET /services or /services.json
  def index
    @services = @business.services
  end

  # GET /services/1 or /services/1.json
  def show
    @activities = @business.activity_log.for_service(service_id: @service.id).limit(8)
  end

  # GET /services/new
  def new
    @service = Service.new
    @activities = @business.activity_log.for_service_team(team: current_user.team).limit(8)

    # flash message if business is unpaid and has 10 services
    flash[:alert] = "You've reached the limits of the free plan. Upgrade to a paid plan in your account settings to add more services." if at_limit?
  end

  # TODO: scope to current user business
  # GET /services/1/edit
  def edit
    @activities = @business.activity_log.for_service(service_id: @service.id).limit(8)
  end

  # POST /services or /services.json
  # rubocop:disable Metrics/MethodLength
  def create
    if at_limit?
      @service = Service.new
      @activities = @business.activity_log.for_service_team(team: current_user.team).limit(8)

      flash[:alert] = "You've reached the limits of the free plan. Upgrade to a paid plan in your account settings to add more services."

      render :new
    else
      @service = Service.new(service_params.merge({team_id: current_user.team.id, created_by: current_user.id}))

      respond_to do |format|
        if @service.save
          Events::Services::Created.new(record: @service, user: current_user).publish

          format.html { redirect_to @service, notice: "Service was successfully created." }
          format.json { render :show, status: :created, location: @service }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @service.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # TODO: use pluck instead of map
  # Use callbacks to share common setup or constraints between actions.
  def set_service
    teams = @business.teams
    @service = Service.where(public_id: params[:id], team_id: teams.map(&:id)).first
  end

  # Only allow a list of trusted parameters through.
  def service_params
    params.require(:service).permit(:name, :description, :created_by)
  end

  def at_limit?
    !@business.paid? && @business.services.size >= Service::UNPAID_LIMIT
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: @service) do |form| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% @service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-y-8 divide-y divide-gray-200">
    <div class="pt-0">
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Service Information
        </h3>
        <p class="mt-1 text-sm text-gray-500">
          Give each service a unique name. A service can represent databases, search clusters, data pipelines, data lakes, or mobile apps that publish data.
        </p>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="name" class="block text-sm font-medium text-gray-700">
            Name
          </label>
          <div class="mt-1">
            <%= form.text_field :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="description" class="block text-sm font-medium text-gray-700">
            Description
          </label>
          <div class="mt-1">
            <%= form.text_area :description, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="pt-5">
    <div class="flex justify-end">
      <a href="<%= business_path(current_user.business) %>" class="button bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Cancel
      </a>
      <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500">
        Save
      </button>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 bg-white xl:flex xl:px-8">
  <div class="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-64 xl:border-r xl:border-gray-200 bg-white">
    <div class="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">

    <%= render 'shared/left_sidebar' %>

    </div>
  </div>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-6 px-4 sm:px-6 lg:px-8">
      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">

        <%= render 'shared/flashes' %>

        <!-- header -->
        <div class="pb-5 px-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-lg leading-6 font-medium text-gray-600">
            Service: <%= @service.name %>
          </h2>
          <div class="mt-3 sm:mt-0 sm:ml-4 font-medium text-gray-400">
            Use services to group like schemas together.
          </div>
        </div>


        <!-- main area wrapper -->
        <div class="relative inset-0 border-2 border-gray-200 border-solid rounded-lg">

          <!-- main area form -->
          <div class="p-6 bg-white shadow overflow-hidden sm:rounded-md">
            <%= render 'form' %>
          </div>
          <!-- end main area list -->

        </div>
      </div>
      <!-- End main area -->
    </div>
  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 xl:flex xl:px-8">
  <div class="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-64 xl:border-r xl:border-gray-200 bg-white">
    <div class="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">

    <%= render 'shared/left_sidebar' %>

    </div>
  </div>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-6 px-4 sm:px-6 lg:px-8">
      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">

        <%= render 'shared/flashes' %>

        <!-- header -->
        <div class="pb-5 px-2 py-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900">New Service</h2>
          <div class="mt-3 sm:mt-0 sm:ml-4 font-medium text-gray-400">
            Create a new service owned by your team and associated with schemas!
          </div>
        </div>


        <!-- main area wrapper -->
        <div class="relative inset-0 border-2 border-gray-200 border-solid rounded-lg">

          <!-- main area form -->
          <div class="p-6 bg-white shadow overflow-hidden sm:rounded-md">
            <%= render 'form' %>
          </div>
          <!-- end main area list -->

        </div>
      </div>
      <!-- End main area -->
    </div>
  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>

app/views/services/show.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 bg-white xl:flex xl:px-8">
  <div class="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-64 xl:border-r xl:border-gray-200 bg-white">
    <div class="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">

    <%= render 'shared/left_sidebar' %>

    </div>
  </div>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-6 px-4 sm:px-6 lg:px-8">
      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">

        <%= render 'shared/flashes' %>

        <!-- header -->
        <div class="pb-5 px-2 py-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900"><%= @service.name %></h2>
          <div class="mt-3 sm:mt-0 sm:ml-4 font-medium text-gray-400">
            <a href="<%= edit_service_path(@service) %>">
              <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
                Edit Service
              </button>
            </a>
          </div>
        </div>

        <!-- main area section -->
        <div class="relative my-6 inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <div class="p-6 bg-white shadow overflow-hidden sm:rounded-md">
            <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
              <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="mt-2">
                  <p class="text-md font-medium text-gray-400">
                    Description: <%= @service.description %>
                  </p>
                </div>
              </div>
            </div>

            <div class="p-4">
              <ul>
                <li>Team: <%= @service.team.name %></li>
                <li>Created at: <%= @service.created_at.to_s %></li>
                <li>Created by: <%= @service.creator.email %></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- end main area section -->

        <!-- main area section -->
        <div class="relative my-6 inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <div class="p-6 bg-white shadow overflow-hidden sm:rounded-md">
            <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
              <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="mt-2">
                  <p class="text-md font-medium text-gray-900">
                    Schemas: 
                  </p>

                  <p class="text-sm font-small text-gray-400">
                    Schemas associated with the service
                  </p>
                </div>
              </div>
            </div>

            <div class="p-4">
              <ul>
                <% @service.schemas.each do |schema| %>
                  <li><%= link_to schema.name, schema_path(schema) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!-- end main area section -->

      </div>
      <!-- End main area -->
    </div>
  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>