config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  ### API routes
  mount API::Root => "/"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  root "public#index"

  ### Marketing pages
  get "features", to: "public#features"
  get "features/producers", to: "public#producers"
  get "features/consumers", to: "public#consumers"
  get "features/api_admins", to: "public#api_admins"
  get "features/database_admins", to: "public#database_admins"
  get "pricing", to: "public#pricing"
  get "company", to: "public#company"
  get "about", to: "public#company"

  get "docs", to: "public#docs"
  get "status", to: "public#status"

  get "blog", to: "blog#index"
  get "blog/:id", to: "blog#show"
  # get "blog" => redirect("http://medium.com/schemabook")

  get "privacy", to: "public#privacy"
  get "terms", to: "public#terms"

  post "newsletters", to: "newsletters#create"
  get "newsletters", to: "newsletters#update"

  ### Application routes
  get "users", to: redirect("dashboards"), as: :user_root # creates user_root_path, used for after sign in path
  get "dashboards", to: "dashboards#index"
  get "documents", to: "documents#index"
  get "supports", to: "supports#index"

  # profiles (user is the resource)
  get "profiles/:id/edit", to: "profiles#edit", as: :edit_user_profile
  get "profiles/:id", to: "profiles#show", as: :user_profile
  patch "profiles/:id", to: "profiles#update", as: :patch_user_profile

  # stakeholders
  post "stakeholders", to: "stakeholders#create"

  # favorites
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"

  resources :teams, except: :index
  resources :businesses
  resources :services
  resources :schemas, param: :public_id do
    resources :validations, only: :create
    resources :webhooks
    resources :versions do
      resources :comments
    end
  end

  get "checkouts", to: "checkouts#new"
  post "checkouts", to: "checkouts#create"
  get "checkouts/success", to: "checkouts#success"
  get "checkouts/cancel", to: "checkouts#cancel"
  delete "checkouts/delete", to: "checkouts#delete"
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :require_admin, only: [:edit, :update, :destroy]

  def show
    @creator = User.find(@business.created_by)
    @stakeholders = User.where(business_id: @business.id)
    @teams = Team.where(business_id: @business.id)
    @activities = @business.activity_log.for_business(business: @business).limit(8)

    return unless @business.subscription_id

    subscription = Stripe::Subscription.retrieve @business.subscription_id

    @cancelled = subscription[:ended_at].nil? ? nil : Time.at(subscription[:ended_at]).utc.to_date
    @days_until_due = subscription[:days_until_due]
    @next_bill_date = Time.zone.today + @days_until_due.to_i.days
  end

  def edit
    @creator = User.find(@business.created_by)
    @stakeholders = User.where(business_id: @business.id)
    @activities = @business.activity_log.activities.limit(8)
  end

  def update
    respond_to do |format|
      if @business.update(business_params)
        Events::Businesses::Updated.new(business: @business, user: current_user).publish

        format.html { redirect_to @business, notice: "Business was successfully updated." }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "Business was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :street_address, :city, :state, :postal, :country)
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: @business) do |form| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% @business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-y-8 divide-y divide-gray-200">
    <div class="pt-0">
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Business Information
        </h3>
        <p class="mt-1 text-sm text-gray-500">
          Use a permanent address where you can receive mail.
        </p>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label for="first_name" class="block text-sm font-medium text-gray-700">
            Name
          </label>
          <div class="mt-1">
            <%= form.text_field :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>

        <div class="sm:col-span-6">
          <label for="street_address" class="block text-sm font-medium text-gray-700">
            Street address
          </label>
          <div class="mt-1">
            <%= form.text_field :street_address, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="city" class="block text-sm font-medium text-gray-700">
            City
          </label>
          <div class="mt-1">
            <%= form.text_field :city, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="state" class="block text-sm font-medium text-gray-700">
            State / Province
          </label>
          <div class="mt-1">
            <%= form.text_field :state, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="zip" class="block text-sm font-medium text-gray-700">
            ZIP / Postal
          </label>
          <div class="mt-1">
            <%= form.text_field :postal, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="country" class="block text-sm font-medium text-gray-700">
            Country / Region
          </label>
          <div class="mt-1">
            <%= form.select :country, ["United States", "Canada", "Mexico"], {}, { class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" } %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="flex justify-end">
      <a href="<%= business_path(@business) %>" class="button bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Cancel
      </a>
      <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500">
        Save
      </button>
    </div>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 bg-white xl:flex xl:px-8">
  <div class="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-64 xl:border-r xl:border-gray-200 bg-white">
    <div class="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">

    <%= render 'shared/left_sidebar' %>

    </div>
  </div>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-6 px-4 sm:px-6 lg:px-8">
      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">

        <%= render 'shared/flashes' %>

        <!-- header -->
        <div class="pb-5 px-2 py-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900"><%= @business.name %></h2>
          <div class="mt-3 sm:mt-0 sm:ml-4 font-medium text-gray-400">
            Schemabook appreciates <%= @business.name %>!
          </div>
        </div>

        <!-- business info area wrapper -->
        <div class="relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <!-- main area form -->
          <div class="p-6 bg-white shadow overflow-hidden sm:rounded-md">
            <%= render 'form' %>
          </div>
        </div>
        <!-- end business info area -->

        <!-- payment area -->
        <div class="mt-8 relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <div class="p-6 bg-white shadow overflow-hidden sm:rounded-md">
            <div class="space-y-8 divide-y divide-gray-200">
              <div class="pt-0">
                <div>
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                  Payment Information
                  </h3>
                  <p class="mt-1 text-sm text-gray-500">
                    We use Stripe for all subscription billing.
                  </p>
                </div>
                <div class="pt-0 product">
                  <div>
                    <h5>$200.00 / month</h5>
                  </div>
                </div>

                <% if @business.subscribed? %>
                <div class="pt-4 product">
                  <div class="pt-5">
                    <h5>Thank you for being a Schemabook customer. We appreciate everyone that supports us.</h5>
                    <h5>You subscribed on: <%= @business.subscribed_at.to_date.to_s(:long) %></h5>
                    <% if @business.cancelled? %>
                      <h5>You cancelled on: <%= @business.cancelled_at.to_date.to_s(:long) %></h5>
                    <% end %>
                  </div>

                  <% unless @business.cancelled? %>
                  <div class="flex justify-end">
                    <%= form_tag(checkouts_delete_path, method: :delete) do %>
                      <button id="checkout-and-portal-button" type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500">
                        Cancel Subscription
                      </button>
                    <% end %>
                  </div>
                  <% end %>
                </div>
                <% else %>
                <div class="pt-0">
                  <div class="pt-5">
                    <div class="flex justify-end">

                    <form action="/checkouts" method="GET">
                      <!-- Add a hidden field with the lookup_key of your Price -->
                      <button id="checkout-and-portal-button" type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500">
                      Subscribe
                      </button>
                    </form>
                    </div>
                  </div>
                </div>
              <% end %>

              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end payment area -->

  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Businesses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 bg-white xl:flex xl:px-8">
  <div class="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-64 xl:border-r xl:border-gray-200 bg-white">
    <div class="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">

      <%= render 'shared/left_sidebar' %>

    </div>
  </div>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-6 px-4 sm:px-6 lg:px-8">
      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">

        <%= render 'shared/flashes' %>

        <!-- header -->
        <div class="pb-5 px-2 py-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900"><%= @business.name %></h2>
          <div class="mt-3 sm:mt-0 sm:ml-4 font-medium text-gray-600">
            Schemabook appreciates <%= @business.name %>!
          </div>
        </div>

        <!-- main area wrapper -->
        <div class="relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <!-- main area list -->
          <div class="bg-white shadow overflow-hidden sm:rounded-md">
            <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
              <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="ml-4 mt-2">
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                    Info
                  </h3>
                </div>
                <div class="ml-4 mt-2 flex-shrink-0">
                  <% if current_user.admin? %>
                  <a href="<%= edit_business_path(@business) %>">
                    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
                      Edit Info
                    </button>
                  </a>
                <% end %>
                </div>
              </div>
            </div>

            <div class="p-4">
              <ul>
                <li><%= @business.street_address %></li>
                <li><%= "#{@business.city}," if @business.city %> <%= @business.state %> <%= @business.postal %></li>
              </ul>
            </div>
            <div class="p-4">
              <ul>
                <li>Created by: <%= @creator.email %></li>
                <li>Created on: <%= l @business.created_at, format: :sample %></li>
              </ul>
            </div>
          </div>
          <!-- end main area list -->
        </div>
        <!-- end main area wrapper -->

        <!-- main area wrapper -->
        <div class="my-8 relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <!-- main area list -->
          <div class="bg-white shadow overflow-hidden sm:rounded-md">
            <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
              <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="ml-4 mt-2">
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                    Payment Details
                  </h3>
                </div>
                <div class="ml-4 mt-2 flex-shrink-0">
                  <% if current_user.admin? %>
                  <a href="<%= edit_business_path(@business) %>">
                    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
                      Edit Info
                    </button>
                  </a>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="p-4">
              <% if !@business.subscribed? %>
              <ul>
                <li>Payment plans are now available allowing your organization to define more than <%= Schema::UNPAID_LIMIT %> schemas. Thank you for supporting what we are building.</li>
                <li>&nbsp;</li>
                <li><%= "You have creatd #{current_user.business.schemas.count} out of #{Schema::UNPAID_LIMIT} schemas" %></li>
                <li><%= "You have creatd #{current_user.business.services.count} out of #{Service::UNPAID_LIMIT} services" %></li>
              </ul>
            <% else %>
              <p>
              You are subscribed as of <%= @business.subscribed_at.to_date.to_s(:long) %> and have an unlimited number of schemas and users.
              </p>
              <br/>
              <% if @cancelled.nil? %>
                <p>
                Your next bill date is <%= @next_bill_date.to_s(:long) %>.
                </p>
              <% else %>
                <p>
                Your subscription was cancelled on: <%= @cancelled %>
                </p>
              <% end %>
            <% end %>
            </div>
          </div>
          <!-- end main area list -->
        </div>
        <!-- end main area wrapper -->


        <!-- main area wrapper -->
        <div class="my-8 relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <!-- main area list -->
          <div class="bg-white shadow overflow-hidden sm:rounded-md">

            <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
              <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="ml-4 mt-2">
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                    Teams
                  </h3>
                </div>
                <div class="ml-4 mt-2 flex-shrink-0">
                  <% if current_user.admin? %>
                  <a href="<%= new_team_path %>">
                    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
                      Create Team
                    </button>
                  </a>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="p-4">
              <ul id="teams">
                <% @teams.each do |team| %>
                <li><%= link_to team.name, team_path(team) %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <!-- end main area list -->

        </div>
        <!-- end main area wrapper -->

        <!-- main area wrapper -->
        <div class="my-8 relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <!-- main area list -->
          <div class="bg-white shadow overflow-hidden sm:rounded-md">

           <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
              <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="ml-4 mt-2">
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                    Teammates
                  </h3>
                </div>
                <div class="ml-4 mt-2 flex-shrink-0">
                  <a href="<%= new_user_invitation_path %>">
                    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
                      Invite Teammate
                    </button>
                  </a>
                </div>
              </div>
            </div>
           <div class="p-4">

              <ul id="stakeholders">
                <% @stakeholders.each do |stakeholder| %>
                <li><%= link_to stakeholder.email, user_profile_path(stakeholder) %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <!-- end main area list -->
        </div>
        <!-- end main area wrapper -->

      </div>
      <!-- End main area -->

    </div>
  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>