config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  ### API routes
  mount API::Root => "/"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  root "public#index"

  ### Marketing pages
  get "features", to: "public#features"
  get "features/producers", to: "public#producers"
  get "features/consumers", to: "public#consumers"
  get "features/api_admins", to: "public#api_admins"
  get "features/database_admins", to: "public#database_admins"
  get "pricing", to: "public#pricing"
  get "company", to: "public#company"
  get "about", to: "public#company"

  get "docs", to: "public#docs"
  get "status", to: "public#status"

  get "blog", to: "blog#index"
  get "blog/:id", to: "blog#show"
  # get "blog" => redirect("http://medium.com/schemabook")

  get "privacy", to: "public#privacy"
  get "terms", to: "public#terms"

  post "newsletters", to: "newsletters#create"
  get "newsletters", to: "newsletters#update"

  ### Application routes
  get "users", to: redirect("dashboards"), as: :user_root # creates user_root_path, used for after sign in path
  get "dashboards", to: "dashboards#index"
  get "documents", to: "documents#index"
  get "supports", to: "supports#index"

  # profiles (user is the resource)
  get "profiles/:id/edit", to: "profiles#edit", as: :edit_user_profile
  get "profiles/:id", to: "profiles#show", as: :user_profile
  patch "profiles/:id", to: "profiles#update", as: :patch_user_profile

  # stakeholders
  post "stakeholders", to: "stakeholders#create"

  # favorites
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"

  resources :teams, except: :index
  resources :businesses
  resources :services
  resources :schemas, param: :public_id do
    resources :validations, only: :create
    resources :webhooks
    resources :versions do
      resources :comments
    end
  end

  get "checkouts", to: "checkouts#new"
  post "checkouts", to: "checkouts#create"
  get "checkouts/success", to: "checkouts#success"
  get "checkouts/cancel", to: "checkouts#cancel"
  delete "checkouts/delete", to: "checkouts#delete"
end

app/views/shared/_activity.erb
<li class="py-4">
  <div class="flex space-x-3">
    <div class="h-10 w-10">
      <%= avatar(activity.user, size: 100) %>
    </div>
    <div class="flex-1 space-y-1">
      <div class="flex-1 items-center justify-between">
        <h3 class="flex-1 text-sm"><%= activity.user.display_name %></h3>
        <p class="text-sm text-gray-500"><%= time_ago_in_words(activity.created_at, include_seconds: true) %> ago</p>
      </div>
      <!-- display information based on type of resource -->
      <h3 class="text-sm font-medium"><%= activity_title(activity) %></h3>
      <p class="text-sm text-gray-500"><%= activity_content(activity) %></p>
    </div>
  </div>
</li>

app/views/shared/_activity_feed.erb
<!-- Start right column area -->
<div class="h-full relative" style="min-height: 16rem;">
  <div class="inset-0 rounded-lg">
    <div>
      <ul id="activities" class="divide-y divide-gray-200">
        <% if @activities.present? %>
          <% @activities.each do |activity| %>
            <%= render partial: 'shared/activity', locals: { activity: activity } %>
          <% end %>
        <% else %>
          <li class="py-4">
            <div class="flex">
              <div class="h-10 w-10">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <div class="flex-1 space-y-1">
                <div class="flex items-center justify-between">
                  <h3 class="text-sm font-medium">Coming soon!</h3>
                </div>
                <p class="text-sm text-gray-500">As contextual activities happen, they will be displayed here to keep the whole team up to date.</p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>
<!-- End right column area -->

app/views/shared/_alert.html.erb
<div class="flash mb-4 rounded-md bg-red-50 p-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <!-- Heroicon name: solid/x-circle -->
      <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <p id="alert" class="text-sm font-medium text-red-800">
        <%= alert %>
      </p>
    </div>
    <div class="ml-auto pl-3">
      <div class="-mx-1.5 -my-1.5">
        <button type="button" class="dismiss inline-flex bg-red-50 rounded-md p-1.5 text-red-500 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-red-50 focus:ring-red-600">
          <span class="sr-only">Dismiss</span>
          <!-- Heroicon name: solid/x -->
          <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<%=
if notice.present?
  render 'shared/notice'
elsif alert.present?
  render 'shared/alert'
end %>

app/views/shared/_left_sidebar.html.erb
<!-- Start left column area -->
<div class="h-full relative" style="min-height: 12rem;">
  <div class="h-full w-full absolute inset-0 text-gray-700">

    <div class="h-full flex min-h-0 flex-1 flex-col bg-white">
      <div class="h-full flex flex-1 flex-col overflow-y-auto pt-0">

        <div>
          <ul class="divide-y divide-gray-200">
            <li class="py-4">
              <div id="add-schema" class="w-full grid">
                <div class="py-2">
                  <span class="text-gray-400">Publish Schema</span>
                </div>
                <div class="absolute right-0">
                  <a href="<%= new_schema_path %>">
                    <button id="new-version" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m3.75 9v6m3-3H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                      </svg>
                    </button>
                  </a>
                </div>
              </div>
            </li>
            <li class="py-4">
              <div id="add-service" class="w-full grid">
                <div class="py-2">
                  <span class="text-gray-400">Define Service</span>
                </div>
                <div class="absolute right-0">
                  <a href="<%= new_service_path %>">
                    <button id="new-version" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>
                    </button>
                  </a>
                </div>
              </div>
            </li>
            <li class="py-4">
              <div id="add-team" class="w-full grid">
                <div class="py-2">
                  <span class="text-gray-400">Invite Teammate</span>
                </div>
                <div class="absolute right-0">
                  <a href="<%= new_user_invitation_path %>">
                    <button id="new-version" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
                      </svg>
                    </button>
                  </a>
                </div>
              </div>
            </li>
            <li class="py-4">
              <div id="account-settings" class="w-full grid">
                <div class="py-2">
                  <span class="text-gray-400">Account Settings</span>
                </div>
                <div class="absolute right-0">
                  <a href="<%= business_path(current_user.business) %>">
                    <button id="new-version" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" />
                      </svg>
                    </button>
                  </a>
                </div>
              </div>
            </li>
            <li class="py-4">
              <div id="log-out" class="w-full grid">
                <div class="py-2">
                  <span class="text-gray-400">Log out</span>
                </div>
                <div class="absolute right-0">
                  <a href="<%= destroy_user_session_path %>" rel="nofollow" data-method="delete">
                    <button id="new-version" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5.636 5.636a9 9 0 1012.728 0M12 3v9" />
                      </svg>
                    </button>
                  </a>
                </div>
              </div>
            </li>
          </ul>
        </div>

      </div>
      <div class="flex flex-shrink-0 border-t border-gray-200 p-4">
        <a href="<%= user_profile_path(current_user) %>" class="group block w-full flex-shrink-0">
          <div class="flex items-center">
            <div>
              <%= avatar(current_user, size: 10) %>
            </div>
            <div class="ml-3">
              <p class="text-sm font-medium text-gray-700 group-hover:text-gray-900"><%= truncate(current_user.display_name, length: 19) %></p>
              <p class="text-xs font-medium text-gray-500 group-hover:text-gray-700">View profile</p>
            </div>
          </div>
        </a>
      </div>
    </div>

  </div>
</div>
<!-- End left column area -->

app/views/shared/_notice.html.erb
<div class="flash mb-4 rounded-md bg-green-50 p-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <!-- Heroicon name: solid/check-circle -->
      <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <p id="notice" class="text-sm font-medium text-green-800">
        <%= notice %>
      </p>
    </div>
    <div class="ml-auto pl-3">
      <div class="-mx-1.5 -my-1.5">
        <button type="button" class="dismiss inline-flex bg-green-50 rounded-md p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-50 focus:ring-green-600">
          <span class="sr-only">Dismiss</span>
          <!-- Heroicon name: solid/x -->
          <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>