config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  ### API routes
  mount API::Root => "/"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  root "public#index"

  ### Marketing pages
  get "features", to: "public#features"
  get "features/producers", to: "public#producers"
  get "features/consumers", to: "public#consumers"
  get "features/api_admins", to: "public#api_admins"
  get "features/database_admins", to: "public#database_admins"
  get "pricing", to: "public#pricing"
  get "company", to: "public#company"
  get "about", to: "public#company"

  get "docs", to: "public#docs"
  get "status", to: "public#status"

  get "blog", to: "blog#index"
  get "blog/:id", to: "blog#show"
  # get "blog" => redirect("http://medium.com/schemabook")

  get "privacy", to: "public#privacy"
  get "terms", to: "public#terms"

  post "newsletters", to: "newsletters#create"
  get "newsletters", to: "newsletters#update"

  ### Application routes
  get "users", to: redirect("dashboards"), as: :user_root # creates user_root_path, used for after sign in path
  get "dashboards", to: "dashboards#index"
  get "documents", to: "documents#index"
  get "supports", to: "supports#index"

  # profiles (user is the resource)
  get "profiles/:id/edit", to: "profiles#edit", as: :edit_user_profile
  get "profiles/:id", to: "profiles#show", as: :user_profile
  patch "profiles/:id", to: "profiles#update", as: :patch_user_profile

  # stakeholders
  post "stakeholders", to: "stakeholders#create"

  # favorites
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"

  resources :teams, except: :index
  resources :businesses
  resources :services
  resources :schemas, param: :public_id do
    resources :validations, only: :create
    resources :webhooks
    resources :versions do
      resources :comments
    end
  end

  get "checkouts", to: "checkouts#new"
  post "checkouts", to: "checkouts#create"
  get "checkouts/success", to: "checkouts#success"
  get "checkouts/cancel", to: "checkouts#cancel"
  delete "checkouts/delete", to: "checkouts#delete"
end

app/models/schema.rb
class Schema < ApplicationRecord
  include PublicIdGenerator

  UNPAID_LIMIT = 10

  has_many :stakeholders
  has_many :favorites
  has_many :versions
  has_many :webhooks

  belongs_to :team
  belongs_to :service, optional: true
  belongs_to :format

  validates :name, presence: true, uniqueness: {scope: :service_id}, length: {in: 2..120}

  def url
    domain = $request.try(:base_url).nil? ? "" : $request.try(:base_url)

    "#{domain}/schemas/#{public_id}"
  end
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController
  def show
    @schema = current_user.team.schemas.find_by!(public_id: params[:public_id])
    @tab = params[:tab] || @schema.format.to_s
    @activities = @business.activity_log.for_schema(schema: @schema).limit(8)
    @stakeholder = Stakeholder.find_or_initialize_by(user_id: current_user.id, schema_id: @schema.id)
    @stakeholders = Stakeholder.where(schema_id: @schema.id)

    version_index = params[:version] || @schema.versions.last.index
    @version = @schema.versions.find_by(index: version_index)

    @comment = Comment.new(version: @version)
    @comments = @version.comments.order(created_at: :desc)

    load_presenters
  end

  def new
    @schema = Schema.new
    @activities = @business.activity_log.for_schema_new.limit(8)

    # flash message if business is unpaid and has 10 schemas
    flash[:alert] = "You've reached the limits of the free plan. Upgrade to a paid plan in your account settings to add more schemas." if at_limit?
  end

  # rubocop:disable Metrics/MethodLength
  def create
    _service = schema_params.key?(:service_id) && @business.services.find(schema_params[:service_id])

    @format = Format.create(format_params)
    @schema = Schema.new(schema_params.merge(format_id: @format.id))

    if at_limit?
      flash[:alert] = "You've reached the limits of the free plan. Upgrade to a paid plan in your account settings to add more schemas."
      @format.destroy

      render :new
    elsif @schema.save && (@version = create_version(schema: @schema))
      Events::Schemas::Created.new(record: @schema, user: current_user).publish

      flash[:info] = "Schema has been saved"
      redirect_to schema_path(@schema)
    else
      flash[:alert] = "Schema could not be saved; body contents were not valid"

      @schema.destroy if @schema.persisted?
      @format.destroy

      render :new
    end
  end
  # rubocop:enable Metrics/MethodLength

  private

  def format_params
    params.require(:schema).permit(:file_type)
  end

  def schema_params
    params.require(:schema).permit(:name, :service_id, :description, :production).merge(team_id: current_user.team.id)
  end

  def version_params
    params.require(:schema).permit(:body)
  end

  def load_presenters
    @json_presenter = JsonPresenter.new(@schema, @version)
    @avro_presenter = AvroPresenter.new(@schema, @version)
    @csv_presenter = CsvPresenter.new(@schema, @version)
    @sql_presenter = SqlPresenter.new(@schema, @version)
  end

  def create_version(schema:)
    # NOTE: this will fail if the body contents are not valid for the format selected
    version = Version.new(version_params.merge(schema_id: schema.id).except(:body))
    version.body = version_params[:body]

    if version.valid?
      version.save

      version
    else
      flash[:alert] = "The schema is not formatted correctly and could not be saved." unless version.valid?

      false
    end
  end

  def at_limit?
    !@business.paid? && @business.schemas.size >= Schema::UNPAID_LIMIT
  end
end

app/helpers/schemas_helper.rb
module SchemasHelper
end

app/views/schemas/_avro.html.erb
<div id="gutter" class="absolute -ml-4 border-r-1">
  <% @avro_presenter.content_length.times do |count| %>
    <div class="bg-gray-100 text-right text-gray-400"><%= count + 1 %></div>
  <% end %>
</div>

<pre class="font-mono ml-4">
<%= @avro_presenter.content %>
</pre>

app/views/schemas/_comment_form.html.erb
<div class="flex items-start space-x-4">
  <div class="flex-shrink-0">
    <%= avatar(current_user, size: 10) %>
  </div>
  <div class="min-w-0 flex-1">
    <%= form_with model: [@schema, @version, @comment], class: "relative" do |form| %>
      <div class="border border-gray-300 rounded-lg shadow-sm overflow-hidden focus-within:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500">
        <%= form.label :body, for: "comment", class: "sr-only", value: "Add your comment" %>
        <%= form.text_area :body, rows: 3,  class: "block w-full py-3 border-0 resize-none focus:ring-0 sm:text-sm", placeholder: "Add your comment" %>
        <%= form.hidden_field :schema_id, value: @schema.id %>
        <%= form.hidden_field :version_id, value: @version.id %>

        <!-- Spacer element to match the height of the toolbar -->
        <div class="py-2" aria-hidden="true">
          <!-- Matches height of button in toolbar (1px border + 36px content height) -->
          <div class="py-px">
            <div class="h-9"></div>
          </div>
        </div>
      </div>

      <div class="absolute bottom-0 inset-x-0 pl-3 pr-2 py-2 flex justify-between">
        <div class="flex items-center space-x-5">
        </div>
        <div class="flex-shrink-0">
          <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-cyan-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">Post</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/schemas/_comments.html.erb
<!-- main area comments section -->
<div class="mb-8 relative inset-0 bg-white">
  <div class="pb-5 border-b border-gray-200">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Comments
    </h3>
  </div>

  <div class="p-4">
    <%= render partial: 'comment_form' %>
  </div>

  <div class="p-4">
    <%= render partial: 'comments_list' %>
  </div>
</div>

app/views/schemas/_csv.html.erb
<div id="gutter" class="absolute -ml-4 border-r-1">
  <% @csv_presenter.content_length.times do |count| %>
    <div class="bg-gray-100 text-right text-gray-400"><%= count + 1 %></div>
  <% end %>
</div>

<pre class="font-mono ml-4">
<%= @csv_presenter.content %>
</pre>

app/views/schemas/_form.html.erb
<%= form_with(model: @schema) do |form| %>

  <div class="space-y-8 divide-y divide-gray-200">
    <div class="pt-0">
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Schema Information
        </h3>
        <p class="mt-1 text-sm text-gray-500">
        We'll give this schema a unique identifier.
        </p>
      </div>
      <% if @schema.errors.any? %>
        <div id="error_explanation" class="mt-4">

          <% if @schema&.format&.json? %>
            <p class="mt-1 text-sm text-red-900">
              Schemabook currently validates against <%= JsonValidator::DRAFT %> of JSON Schema.
            </p>
          <% end %>

          <p class="mt-1 text-sm text-red-900">
            <%= pluralize(@schema.errors.count, "error") %> prohibited this schema from being saved:
          </p>

          <ul>
            <% @schema.errors.each do |error| %>
              <li class="py-1 px-2 mt-1 text-sm text-red-900">
                <%= error.full_message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="first_name" class="block text-sm font-medium text-gray-700">
            Name*
          </label>
          <div class="mt-1">
            <%= form.text_field :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="first_name" class="block text-sm font-medium text-gray-700">
            Production data*
          </label>
          <div class="mt-1">
            <%= form.select :production, [true, false], {}, { class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" } %>
          </div>
        </div>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-8">
        <div class="sm:col-span-3">
          <label for="format" class="block text-sm font-medium text-gray-700">
            Schema Format*
          </label>
          <div class="mt-1">
            <%= form.select :file_type, Format.file_types.keys, {}, { class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" } %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="service" class="block text-sm font-medium text-gray-700">
            Service (optional)
          </label>
          <div class="mt-1">
            <%= form.select :service_id, current_user.team.services.map { |service| [service.name, service.id] }, {}, { class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" } %>
          </div>
        </div>
      </div>

    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="service" class="block text-sm font-medium text-gray-700">
            Description (optional)
          </label>
          <div class="mt-1">
            <%= form.text_area :description, cols: 20, rows: 10, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="service" class="block text-sm font-medium text-gray-700">
            Body*
          </label>
          <div class="mt-1">
            <%= form.text_area :body, cols: 20, rows: 40, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="pt-5 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <div class="sm:col-span-3 justify-right">
      <a href="<%= schemas_path %>" class="button bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Cancel
      </a>
      <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500">
        Save
      </button>
    </div>
  </div>
<% end %>

app/views/schemas/_json.html.erb
<div id="gutter" class="absolute -ml-4 border-r-1">
  <% @json_presenter.content_length.times do |count| %>
    <div class="bg-gray-100 text-right text-gray-400"><%= count + 1 %></div>
  <% end %>
</div>

<pre class="font-mono ml-4">
<%= @json_presenter.content %>
</pre>

app/views/schemas/_sql.html.erb
<div id="gutter" class="absolute -ml-4 border-r-1">
  <% @sql_presenter.content_length.times do |count| %>
    <div class="bg-gray-100 text-right text-gray-400"><%= count + 1 %></div>
  <% end %>
</div>

<pre class="font-mono ml-4">
<%= @sql_presenter.content %>
</pre>

app/views/schemas/_stakeholders.html.erb
<% if @stakeholder.persisted? %>
  <div class="w-full grid grid-rows-2 grid-flow-col">
    <div class="py-2">
      <span class="text-gray-400">Stakeholders:</span> <span class="stakeholder-count"><%= @stakeholders.size %></span>
    </div>
    <span class"text-teal-400">You are a <%= link_to "stakeholder", user_profile_path(current_user), { class: "underline" } %></span>
  </div>
<% else %>
  <div id="add-stakeholder" class="w-full grid">
    <div class="py-2">
      <span class="text-gray-400">Stakeholders:</span> <span class="stakeholder-count"><%= @stakeholders.size %></span>
    </div>
    <div class="absolute right-0">
      <%= form_for @stakeholder, url: stakeholders_path(@stakeholder), html: { method: :post }, remote: true do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :schema_id, value: @schema.id %>

        <button id="new-stakeholder" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
          <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
          </svg>
        </button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/schemas/_tab_content.html.erb
<!-- main area list -->
<div id="tab-content" class="tabcontent bg-gray-100 inset-0 p-6 shadow sm:rounded-md">
  <% if @tab == 'json' %>
    <%= render partial: 'json' %>
  <% end %>

  <% if @tab == 'avro' %>
    <%= render partial: 'avro' %>
  <% end %>

  <% if @tab == 'csv' %>
    <%= render partial: 'csv' %>
  <% end %>

  <% if @tab == 'sql' %>
    <%= render partial: 'sql' %>
  <% end %>

  <% if @tab == 'info' %>
    <%= render partial: 'info' %>
  <% end %>
</div>
<!-- end main area list -->

app/views/schemas/_tabs.html.erb
<nav class="-mb-px flex space-x-8" aria-label="Tabs">
  <% highlight = 'border-teal-500' %>
  <a href="/schemas/<%= @schema.public_id %>?tab=json<%= "&version=#{params[:version]}" if params[:version] %>" class="<%= @tab == 'json' ? highlight : 'border-transparent' %> text-teal-600 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
    JSON
  </a>
  <a href="/schemas/<%= @schema.public_id %>?tab=avro<%= "&version=#{params[:version]}" if params[:version] %>" class="has-tooltip <%= @tab == 'avro' ? highlight : 'border-transparent' %> text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
    <span class='tooltip rounded shadow-lg p-1 bg-gray-100 text-grey-500 -mt-8'>Avro is a compact and efficient binary file format displayed as JSON</span>
    Avro
  </a>
  <a href="/schemas/<%= @schema.public_id %>?tab=csv<%= "&version=#{params[:version]}" if params[:version] %>" class="<%= @tab == 'csv' ? highlight : 'border-transparent' %> text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
    CSV
  </a>
  <a href="/schemas/<%= @schema.public_id %>?tab=sql<%= "&version=#{params[:version]}" if params[:version] %>" class="<%= @tab == 'sql' ? highlight : 'border-transparent' %> text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
    SQL
  </a>

  <a href="/schemas/<%= @schema.public_id %>?tab=info<%= "&version=#{params[:version]}" if params[:version] %>" class="<%= @tab == 'info' ? highlight : 'border-transparent' %> md:absolute md:right-8 border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
    General Information
  </a>
</nav>

app/views/schemas/_versions.html.erb
<div id="add-version" class="w-full grid">
  <div class="py-2">
    <span class="text-gray-400">Versions:</span> <%= @schema.versions.count %>
  </div>
  <% if @schema.team.users.include?(current_user) %>
  <div class="absolute right-0">
    <a href="<%= new_schema_version_path(@schema) %>">
      <button id="new-version" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
        <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m3.75 9v6m3-3H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
      </button>
    </a>
  </div>
  <% end %>
  <% if @schema.versions.count > 1 %>
  <div class="py-2">
    <span class="text-gray-400 text-sm italic">
    View General Information for previous versions</span>
  </div>
  <% end %>
</div>

app/views/schemas/_webhooks.html.erb
<div id="add-webhook" class="w-full grid">
  <div class="py-2">
    <span class="text-gray-400">Webhooks:</span> <%= @schema.webhooks.count %>
  </div>
  <% if @schema.team.users.include?(current_user) %>
  <div class="absolute right-0">
    <a href="<%= new_schema_webhook_path(@schema) %>">
      <button id="new-webhook" type="submit" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
        <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m3.75 9v6m3-3H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
      </button>
    </a>
  </div>
  <% end %>
  <% if @schema.webhooks.count > 1 %>
  <div class="py-2">
    <span class="text-gray-400 text-sm italic">
    View General Information for previous webhooks</span>
  </div>
  <% end %>
</div>

app/views/schemas/new.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 bg-white xl:flex xl:px-8">
  <div class="border-b border-gray-200 xl:border-b-0 xl:flex-shrink-0 xl:w-64 xl:border-r xl:border-gray-200 bg-white">
    <div class="h-full pl-4 pr-6 py-6 sm:pl-6 lg:pl-8 xl:pl-0">
      <%= render 'shared/left_sidebar' %>
    </div>
  </div>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-6 px-4 sm:px-6 lg:px-8">
      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">
        <%= render 'shared/flashes' %>

        <!-- header -->
        <div class="pb-5 px-2 py-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900">New Schema</h2>
          <div class="mt-3 sm:mt-0 sm:ml-4 font-medium text-gray-400">
            Schemabook appreciates <%= current_user.business.name %>!
          </div>
        </div>


        <!-- main area wrapper -->
        <div class="relative inset-0 border-2 border-gray-200 border-solid rounded-lg">

          <!-- main area form -->
          <div class="p-6 w-full bg-white shadow overflow-hidden sm:rounded-md">
            <%= render 'form' %>
          </div>
          <!-- end main area list -->

        </div>
      </div>
      <!-- End main area -->
    </div>
  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>

app/views/schemas/show.html.erb
<!-- Left sidebar & main wrapper -->
<div class="flex-1 min-w-0 bg-white xl:flex xl:px-8">
  <%= render partial: 'sidebar' %>

  <div class="bg-white lg:min-w-0 lg:flex-1">
    <div class="h-full py-4 px-4 sm:px-6 lg:px-8">

      <!-- Start main area-->
      <div class="relative h-full" style="min-height: 36rem;">

        <div class="mt-4">
          <%= render 'shared/flashes' %>
        </div>

        <!-- header -->
        <div class="pb-5 px-2 sm:flex sm:items-center sm:justify-between">
          <h2 class="text-2xl font-bold leading-10 tracking-tight text-gray-900"><%= @schema.name %></h2>
          <div class="text-md text-gray-400 mt-3 sm:mt-0 sm:ml-4">
            <span class="text-gray-400">Version:</span> <%= @version.index %>
          </div>
        </div>

        <div class="mb-8 relative inset-0 border-2 border-gray-200 border-solid rounded-lg">
          <div>
            <div class="hidden sm:block">
              <div class="px-4 border-b border-gray-200">
                <%= render partial: 'tabs' %>
              </div>
            </div>
          </div>

          <%= render partial: 'tab_content' %>
        </div>

        <%= render partial: 'comments' %>

      </div>
      <!-- End main area -->

    </div>
  </div>
</div>

<div class="bg-gray-50 pr-4 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-8">
  <div class="pl-6 py-6 lg:w-80">
    <%= render partial: 'shared/activity_feed' %>
  </div>
</div>